_format_version: "2.1"
_transform: true

routes:
- name: route-auth
  protocols:
  - http
  paths:
  - /auth
  strip_path: true
  preserve_host: false
  regex_priority: 1
  service: service-auth

services:
- name: service-auth
  host: upstream-auth
  protocol: http
  port: 80
  connect_timeout: 60000
  read_timeout: 60000
  write_timeout: 60000
  retries: 5

upstreams:
- name: upstream-auth
  algorithm: round-robin

targets:
- upstream: upstream-auth
  target: auth-auth-1:3000
  weight: 100

plugins:
- config:
    generator: tracker
    header_name: X-Kong-Request-ID
    echo_downstream: true
  name: correlation-id
